/* ─────────────────────────────────────────────
   NUTTI 상품 데이터 (products-data.js)
   - 가격(도매/소매) 정보는 보안상 클라이언트 코드에 두지 않는다.
   - url: 자사몰(nutti.co.kr) 상품 상세 경로. 비어 있으면 바로가기 미노출.
     예) url:'/product/detail.html?product_no=123'
   - 실 판매 제품 교체(Phase 1) 시 이 파일만 수정하면 된다.
   ───────────────────────────────────────────── */
var PRODUCTS = [
  {id:1, name:'소창개껌스틱 30cm (2p)', weight:'2p', url:'',
   texture:'MIDDLE', texVal:2, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🦴', color:'#FAE8DC', cat:'mixed', catLabel:'혼합',
   ingredients:'철분, 비타민, 필수지방산',
   functions:['빈혈','피부','노화방지','알러지예방']},
  {id:2, name:'소창개껌스틱 20g', weight:'20g', url:'',
   texture:'MIDDLE', texVal:2, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🦴', color:'#FAE8DC', cat:'mixed', catLabel:'혼합',
   ingredients:'철분, 비타민, 필수지방산',
   functions:['빈혈','피부','노화방지','알러지예방']},
  {id:3, name:'상어연골', weight:'70g', url:'',
   texture:'HARD', texVal:3, age:[2], size:[3,4],
   emoji:'🦈', color:'#E6F1FB', cat:'bone', catLabel:'뼈·연골',
   ingredients:'콘드로이틴, 뮤코다당, 칼슘, 특수단백질',
   functions:['관절','골다공증','뼈건강','신경통']},
  {id:4, name:'리얼 오리져키', weight:'100g', url:'',
   texture:'MIDDLE', texVal:2, age:[1,2], size:[2,3,4],
   emoji:'🦆', color:'#FAE8DC', cat:'meat', catLabel:'육류',
   ingredients:'필수지방산, 필수아미노산, 단백질',
   functions:['알러지예방','두뇌','피부']},
  {id:5, name:'오리몸통', weight:'1p', url:'',
   texture:'HARD', texVal:3, age:[2], size:[2,3,4],
   emoji:'🦆', color:'#FAE8DC', cat:'meat', catLabel:'육류',
   ingredients:'단백질, 무기질, 비타민',
   functions:['다이어트','빈혈','기력']},
  {id:6, name:'단호박 츄러스 SOFT', weight:'100g', url:'',
   texture:'SOFT', texVal:1, age:[1,2], size:[1,2,3,4],
   emoji:'🎃', color:'#FDF3DC', cat:'veggie', catLabel:'채소',
   ingredients:'비타민A, 무기질, 베타카로틴',
   functions:['면역','피부','시력보호','감기예방']},
  {id:7, name:'황태 츄러스 SOFT', weight:'100g', url:'',
   texture:'SOFT', texVal:1, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🐟', color:'#E6F1FB', cat:'fish', catLabel:'수산물',
   ingredients:'아미노산, 고단백, 저지방',
   functions:['다이어트','두뇌','기력','신진대사']},
  {id:8, name:'명태포', weight:'60g', url:'',
   texture:'SOFT', texVal:1, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🐟', color:'#E6F1FB', cat:'fish', catLabel:'수산물',
   ingredients:'아미노산, 고단백, 저지방',
   functions:['다이어트','두뇌','기력','신진대사']},
  {id:9, name:'연어분말 팩', weight:'30g', url:'',
   texture:'분말', texVal:0, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🐠', color:'#E6F1FB', cat:'powder', catLabel:'분말',
   ingredients:'오메가3, 불포화지방산, 비타민D',
   functions:['두뇌','심장','뼈건강','피부']},
  {id:10, name:'황태분말(통)', weight:'70g', url:'',
   texture:'분말', texVal:0, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🐟', color:'#E6F1FB', cat:'powder', catLabel:'분말',
   ingredients:'아미노산, 고단백, 저지방',
   functions:['두뇌','기력','다이어트','신진대사']},
  {id:11, name:'양사골', weight:'4p', url:'',
   texture:'HARD', texVal:3, age:[2], size:[3,4],
   emoji:'🦷', color:'#F3E8FF', cat:'bone', catLabel:'뼈·연골',
   ingredients:'항암물질(CLA), 다이어트 성분',
   functions:['관절','다이어트','알러지예방']},
  {id:12, name:'훈련용 노즈워크 연단고', weight:'100g', url:'',
   texture:'SOFT', texVal:1, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🐾', color:'#F1E9DF', cat:'mixed', catLabel:'훈련용',
   ingredients:'오메가3, 불포화지방산, 비타민D',
   functions:['두뇌','심장','소화','뼈건강']},
  {id:13, name:'연어당근 SOFT (몽땅)', weight:'100g', url:'',
   texture:'SOFT', texVal:1, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🥕', color:'#F1E9DF', cat:'mixed', catLabel:'혼합',
   ingredients:'오메가3, 비타민A, 베타카로틴, 섬유질',
   functions:['두뇌','소화','면역','시력보호','피부']},
  {id:14, name:'리얼 소고기져키', weight:'100g', url:'',
   texture:'MIDDLE', texVal:2, age:[1,2], size:[2,3,4],
   emoji:'🥩', color:'#FCEBEB', cat:'meat', catLabel:'육류',
   ingredients:'철분, 비타민, 고단백, 저지방',
   functions:['빈혈','피부','다이어트','신진대사']},
  {id:15, name:'리얼 참치져키', weight:'100g', url:'',
   texture:'MIDDLE', texVal:2, age:[1,2], size:[2,3,4],
   emoji:'🐟', color:'#E6F1FB', cat:'fish', catLabel:'수산물',
   ingredients:'칼륨, 항염증 비타민, 고단백, 저지방',
   functions:['심장','관절','다이어트','신진대사']},
  {id:16, name:'소허파', weight:'60g × 3', url:'',
   texture:'SOFT', texVal:1, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🫁', color:'#FCEBEB', cat:'meat', catLabel:'육류',
   ingredients:'철분, 비타민, 고단백, 저지방',
   functions:['빈혈','피부','다이어트','신진대사']},
  {id:17, name:'소간', weight:'100g', url:'',
   texture:'MIDDLE', texVal:2, age:[1,2], size:[1,2,3,4],
   emoji:'🫀', color:'#FCEBEB', cat:'meat', catLabel:'육류',
   ingredients:'철분, 비타민, 고단백, 저지방',
   functions:['빈혈','피부','다이어트','신진대사']},
  {id:18, name:'돼지귀 (대용량)', weight:'300g', url:'',
   texture:'MIDDLE', texVal:2, age:[1,2], size:[1,2,3,4],
   emoji:'🐷', color:'#FAE8DC', cat:'meat', catLabel:'육류',
   ingredients:'콜라겐, 비타민, 고단백, 저지방',
   functions:['피부','노화방지','관절','다이어트']},
  {id:19, name:'오메가 MSM + 연어분말(통)', weight:'100g', url:'',
   texture:'분말', texVal:0, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🐠', color:'#E6F1FB', cat:'powder', catLabel:'분말',
   ingredients:'오메가3, 불포화지방산, 비타민D',
   functions:['두뇌','심장','관절','뼈건강']},
  {id:20, name:'소간분말(통)', weight:'70g', url:'',
   texture:'분말', texVal:0, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🫀', color:'#FCEBEB', cat:'powder', catLabel:'분말',
   ingredients:'철분, 고단백, 저지방, 비타민',
   functions:['빈혈','피부','다이어트','신진대사']},
  {id:21, name:'황태포', weight:'50g', url:'',
   texture:'SOFT', texVal:1, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🐟', color:'#E6F1FB', cat:'fish', catLabel:'수산물',
   ingredients:'필수아미노산, 고단백, 저지방',
   functions:['다이어트','두뇌','기력','신진대사']},
  {id:22, name:'황태포 (대용량)', weight:'50g × 3', url:'',
   texture:'SOFT', texVal:1, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🐟', color:'#E6F1FB', cat:'fish', catLabel:'수산물',
   ingredients:'필수아미노산, 고단백, 저지방',
   functions:['다이어트','두뇌','기력','신진대사']},
  {id:23, name:'저온건조 연근(통)', weight:'50g', url:'',
   texture:'HARD', texVal:3, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🌿', color:'#E8F5E1', cat:'veggie', catLabel:'채소',
   ingredients:'비타민C, 식이섬유, 무기질',
   functions:['소화','면역','신진대사']},
  {id:24, name:'저온건조 당근(통)', weight:'50g', url:'',
   texture:'HARD', texVal:3, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🥕', color:'#FDF3DC', cat:'veggie', catLabel:'채소',
   ingredients:'베타카로틴, 비타민A, 식이섬유',
   functions:['다이어트','시력보호','면역','소화']},
  {id:25, name:'저온건조 완두콩(통)', weight:'50g', url:'',
   texture:'HARD', texVal:3, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🫘', color:'#E8F5E1', cat:'veggie', catLabel:'채소',
   ingredients:'단백질, 식이섬유, 비타민K',
   functions:['다이어트','소화','뼈건강']},
  {id:26, name:'저온건조 청무(통)', weight:'50g', url:'',
   texture:'HARD', texVal:3, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🌱', color:'#E8F5E1', cat:'veggie', catLabel:'채소',
   ingredients:'비타민C, 식이섬유, 칼슘',
   functions:['소화','면역','신진대사']},
  {id:27, name:'저온건조 단호박(통)', weight:'50g', url:'',
   texture:'HARD', texVal:3, age:[1,2,3,4], size:[1,2,3,4],
   emoji:'🎃', color:'#FDF3DC', cat:'veggie', catLabel:'채소',
   ingredients:'비타민A, 베타카로틴, 식이섬유',
   functions:['면역','피부','시력보호','소화']},
];
